config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  get '/search', to: 'searches#new'
  post '/search', to: 'searches#show'
  get '/tags/:tag', to: 'posts#index', as: "tag"

  resources :users, only: [:index, :show, :new, :create]
  resources :posts, only: [:index, :show, :new, :create]


  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/association.rb
class Association < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/following.rb
class Following < ApplicationRecord
    belongs_to :person
    belongs_to :follower, :class_name => 'User'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :associations, dependent: :destroy
  has_many :tags, through: :associations

  validates :title, presence: true, length: { minimum: 3, maximum: 255 }
  validates :text, presence: true, length: { minimum: 5, maximum: 1000 }

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
        Tag.where(name: name.strip).first_or_create!
    end
  end
  
  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :associations, dependent: :destroy
    has_many :posts, through: :associations

    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :posts, dependent: :destroy
    has_many :followers, :class_name => 'Followings', :foreign_key => 'person_id'
    has_many :following, :class_name => 'Followings', :foreign_key => 'follower_id' 
    has_one_attached :avatar
    validates :username, presence: true
    validates :full_name, presence: true
    validates :email, presence: true
    validates :password, presence: true

    validate :avatar_format

def resize_image
    resized_image = MiniMagick::Image.read(avatar.download)
    resized_image = resized_image.resize "200x200"
    v_filename = avatar.filename
    v_content_type = avatar.content_type
    avatar.purge
    avatar.attach(io: File.open(resized_image.path), filename:  v_filename, content_type: v_content_type)
end

private
def avatar_format
 return unless avatar.attached?
 if avatar.blob.content_type.start_with? 'image/'
   if avatar.blob.byte_size > 10.megabytes
     errors.add(:avatar, 'size needs to be less than 10MB')
     avatar.purge
   else
     resize_image
   end
  else
    avatar.purge
    errors.add(:avatar, 'needs to be an image')
  end
end

    def user_params
      params.require(:user).permit(:email_address, :password, :avatar)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    def configure_permitted_parameters               
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :cover]) 
    end
    def redirect_if_not_signed_in
        redirect_to root_path if !user_signed_in?
      end
      
      def redirect_if_signed_in
        redirect_to root_path if user_signed_in?
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home 
        @posts = Post.all
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :redirect_if_not_signed_in, only: [:new]
    
    def index
      if params[:tag]
        @posts = Post.tagged_with(params[:tag])
      else
        @posts = Post.all
      end
    end
    
    def new
        @posts = Post.new
      end
    
      def create
        @posts = Post.new(post_params)
        if @posts.save 
          redirect_to post_path(@posts) 
        else
          redirect_to root_path
        end
      end

      def show
        @post = Post.find(params[:id])
      end

      def list
    
        if !params[:tag].nil? # Are we looking at a tag?
          @tag = Tag.find_by_name(params[:tag])
          if @tag.nil?
            # Redirect if user is trying to look at a non-existent tag
            redirect_to root_path
          else           
            @posts = @tag.posts.order("id DESC")
          end
        else
          # No tag - display posts as normal      
          @posts = Post.all.order("id DESC")
        end
                           
      end

    private 
        def get_posts
            Post
        end

        def post_params
            params.require(:post).permit(:title, :text, :all_tags)
                                 .merge(user_id: current_user.id)
          end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
  
    def sign_up_params
      params.require(:user).permit( :email,
          :full_name, 
                                    :username, 
                                    :password,
                                    :avatar)
    end
  
    def account_update_params
      params.require(:user).permit( :email,
                                    :current_password)
    end
  end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def show
        search_term = params['q'].capitalize

        url = "https://poetrydb.org/title/#{params[:q]}/lines.json"
        response = HTTParty.get(url).to_s
        json = JSON.parse(response)
        poem = json[0]["lines"]
        puts poem
        if poem
              @poem = poem
              @title = params[:q]
         else
              render :new
         end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
      end

    def edit 
        @user.avatar.attach(params[:avatar])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'poe', root_path, class: 'navbar-brand' %>    </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
        <ul class="nav navbar-nav ">
          <% if user_signed_in? %>     
      
            <li class="mobile-menu">
              <%= link_to 'Create Post', href="/posts/new" %>
            </li>
            <li class="mobile-menu">
              <%= link_to 'Users', href="/users" %>
            </li>
            <li class="mobile-menu">
            <%= link_to 'Poems', href="/search" %>
          </li>
          <li class="mobile-menu"><%= link_to 'My Profile', user_path(current_user) %></li>
          <li class="mobile-menu"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
      
          <% else # user not signed it %>
            <li ><%= link_to 'Login', login_path %></li>
            <li ><%= link_to 'Signup', signup_path %></li>
          <% end # if user is signed it %>
        </ul>
      </div><!-- navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<%= render @posts.reverse %>

app/views/posts/_post.html.erb
<div class=" single-post-card" id=<%= post_path(post.id) %>>
  <div class="card">
    <div class="card-block">
      <h4 class="post-text">
      </h4>
      <div class="post-content">
             <h1 class="card-header"> <%= link_to post.title, post_path(post.id)%> </h1>

        <strong><%= link_to post.user.username, user_path(post.user_id) %></strong>
        <%= post.created_at.to_date %>
        <p><%= post.text %></p>
        <div class="tags">
        Tags: <%=raw tag_links(post.all_tags)%>
      </div>
      <p> _____________________</p>
      </div>
    </div>

  </div><!-- card -->
</div><!-- col-sm-3 -->

app/views/posts/index.html.erb
<%= render @posts.reverse %>

app/views/posts/new.html.erb
<div class="container new-post">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Create a new post</h1>
        <%= render 'posts/new/post_form' %>
    </div>
  </div>
</div>

app/views/posts/new/_post_form.erb
<%= bootstrap_form_for(@posts) do |f| %>
    <%= f.text_field  :title, 
                      maxlength: 100, 
                      placeholder: 'Title', 
                      class: 'form-control',
                      required: true, 
                      minlength: 3,
                      maxlength: 100 %>
    <%= f.hidden_field :branch, :value => @branch %>
    <%= f.text_area :text, 
                    rows: 6,
                    required: true, 
                    minlength: 5,
                    maxlength: 1000,
                    placeholder: 'Dare to be creative!', 
                    class: 'form-control' %>
                      <%= f.label :all_tags, "Tags (optional)" %>
                      <%= f.text_field :all_tags, placeholder: "Tags separated with comma" %>  
    <%= f.submit "Create a post", class: 'form-control' %>
  <% end %>

app/views/posts/show.html.erb
<h1>Poem: <%= @post.title %></h1>
<p><%= @post.text %></p>
<div class="tags">
Tags: <%=raw tag_links(@post.all_tags)%>
</div>
<p>Posted by <strong><%= link_to @post.user.username, user_path(@post.user_id) %></strong> on <%= @post.created_at.to_date %></p>

app/views/searches/new.html.erb
<h1> Poem Page</h1>
<%= form_tag("/search", method: "post") do %>
  <%= label_tag(:q, "") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/searches/show.html.erb
<h1><%=@title%></h1>
<% @poem.each do |line| %>
    <h3><%= line %></h3>
    <% end %>

app/views/users/index.html.erb
  <div class="card">
    <div class="card-block">
    <h1>All Users</h1>
    <% @users.each do |user| %>
    <h4><%= link_to user.username, user_path(user) %></h4>
    <% end %>
    </div>
  </div><!-- card -->

app/views/users/show.html.erb
<div class="card">
<div class="card-block">
<h1>Profile Page for <%= @user.full_name %></h1>
<div class="form-group">
<div class="row">
  <div class="col-sm-4">
  <% if @user.avatar.attached? %>
    <%= image_tag @user.avatar, class: "rounded-circle" %>
    <% end %>
  </div>
</div>
</div>
<p><%= @user.username %></p>

<p><%= render @user.posts.reverse %></p>

</div>
</div>